apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-nginx-config
  namespace: loki
data:
  nginx.conf: |
    events {}

    http {
      log_format custom '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_scope_orgid"';

      map $http_x_scope_orgid $tenant {
        default $http_x_scope_orgid;
        ""      default-tenant;
      }

      server {
        listen 3100;

        location /loki/api/v1/push {
          limit_except POST {
            deny all;
          }

          proxy_pass http://loki-distributor.loki.svc.cluster.local:3100;
          proxy_set_header X-Scope-OrgID $tenant;
          proxy_set_header Host $host;
          proxy_set_header Authorization $http_authorization;

          access_log /var/log/nginx/access.log custom;

          proxy_connect_timeout 5s;
          proxy_read_timeout 30s;
          proxy_send_timeout 30s;
        }
      }
    }
